###Read all user
GET http://localhost:3000/api/users


###Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json



{
    "username": "Charlie",
    "email": "charlie@exaple.com",
    "password":"pass3345"
}



###Update a user
PUT http://localhost:3000/users/4
Content-Type: application/json

{
    "username": "Earn",
    "email": "WatYaai@exaple.com",
    "password":"Clang"
}