###Read all user
GET http://localhost:3000/api/v2/users  





###Create a new user
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
    "username": "rodan",
    "role": "admin",
    "email": "rodan@exaple.com",
    "password":"pass4455"
}



###Update a user
PUT http://localhost:3000/api/v2/users/6a0ae7659d35d67e11a43250
Content-Type: application/json

{
    "username": "Earn",
    "email": "WatYaai@exaple.com",
    "password":"C_lang"
}



### Get all product
GET http://localhost:3000/api/v1/product/


### Delete by id
DELETE http://localhost:3000/api/v2/users/6a0ae6f69d35d67e11a4324f


