###Read all user
GET http://localhost:3000/api/v2/users  





###Create a new user
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
    "username": "Michelle",
    "role": "admin",
    "email": "Michellelie2@exaple.com",
    "password":"pass4455"
}



###Update a user
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
    "username": "Earn",
    "email": "WatYaai@exaple.com",
    "password":"C_lang"
}



### Get all product
GET http://localhost:3000/api/v1/product/


